export const APARTMENTS_REQUEST = 'APARTMENTS_REQUEST';
export const APARTMENTS_SUCCESS = 'APARTMENTS_SUCCESS';
export const APARTMENTS_FAILURE = 'APARTMENTS_FAILURE';


export const APARTMENT_MATCHES_REQUEST = 'APARTMENT_MATCHES_REQUEST';
export const APARTMENT_MATCHES_SUCCESS = 'APARTMENT_MATCHES_SUCCESS';
export const APARTMENT_MATCHES_FAILURE = 'APARTMENT_MATCHES_FAILURE';
