export const APARTMENTS_REQUEST = 'APARTMENTS_REQUEST';
export const APARTMENTS_SUCCESS = 'APARTMENTS_SUCCESS';
export const APARTMENTS_FAILURE = 'APARTMENTS_FAILURE';

export const APARTMENT_MATCHES_REQUEST = 'APARTMENT_MATCHES_REQUEST';
export const APARTMENT_MATCHES_SUCCESS = 'APARTMENT_MATCHES_SUCCESS';
export const APARTMENT_MATCHES_FAILURE = 'APARTMENT_MATCHES_FAILURE';

export const VALIDATE_ADDRESS_SUCCESS = 'VALIDATE_ADDRESS_SUCCESS';
export const VALIDATE_ADDRESS_FAILURE = 'VALIDATE_ADDRESS_FAILURE';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
