
export const FETCH_NEARBY_CAMPAIGNS_REQUEST = 'FETCH_NEARBY_CAMPAIGNS_REQUEST';
export const FETCH_NEARBY_CAMPAIGNS_SUCCESS = 'FETCH_NEARBY_CAMPAIGNS_SUCCESS';
export const FETCH_NEARBY_CAMPAIGNS_FAILURE = 'FETCH_NEARBY_CAMPAIGNS_FAILURE';

export const VALIDATE_ADDRESS_SUCCESS = 'VALIDATE_ADDRESS_SUCCESS';
export const VALIDATE_ADDRESS_FAILURE = 'VALIDATE_ADDRESS_FAILURE';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';

