export const ADD_SIGNATURE_TO_PETITION_REQUEST = 'ADD_SIGNATURE_TO_PETITION_REQUEST';
export const ADD_SIGNATURE_TO_PETITION_SUCCESS = 'ADD_SIGNATURE_TO_PETITION_SUCCESS';
export const ADD_SIGNATURE_TO_PETITION_FAILURE = 'ADD_SIGNATURE_TO_PETITION_FAILURE';
