export const ADD_SIGNATURE_TO_CAMPAIGN_REQUEST = 'ADD_SIGNATURE_TO_CAMPAIGN_REQUEST';
export const ADD_SIGNATURE_TO_CAMPAIGN_SUCCESS = 'ADD_SIGNATURE_TO_CAMPAIGN_SUCCESS';
export const ADD_SIGNATURE_TO_CAMPAIGN_FAILURE = 'ADD_SIGNATURE_TO_CAMPAIGN_FAILURE';

export const FETCH_SIGNATURES_REQUEST = 'FETCH_SIGNATURES_REQUEST';
export const FETCH_SIGNATURES_SUCCESS = 'FETCH_SIGNATURES_SUCCESS';
export const FETCH_SIGNATURES_FAILURE = 'FETCH_SIGNATURES_FAILURE';
