export const ADD_SIGNATURE_TO_CAMPAIGN_REQUEST = 'ADD_SIGNATURE_TO_CAMPAIGN_REQUEST';
export const ADD_SIGNATURE_TO_CAMPAIGN_SUCCESS = 'ADD_SIGNATURE_TO_CAMPAIGN_SUCCESS';
export const ADD_SIGNATURE_TO_CAMPAIGN_FAILURE = 'ADD_SIGNATURE_TO_CAMPAIGN_FAILURE';
