export const FETCH_SIGNED_CAMPAIGNS_REQUEST = 'FETCH_SIGNED_CAMPAIGNS_REQUEST';
export const FETCH_SIGNED_CAMPAIGNS_SUCCESS = 'FETCH_SIGNED_CAMPAIGNS_SUCCESS';
export const FETCH_SIGNED_CAMPAIGNS_FAILURE = 'FETCH_SIGNED_CAMPAIGNS_FAILURE';
